- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World {{ opt1 }}!"
    - name: stat
      stat:
        path: "/root/Spectrum_Scale_Data_Management-5.0.5.3-x86_64-Linux-install"


