- name: Hello World Sample
  hosts: ansible
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World {{ opt1 }}!"
    - name: shell
      command: /usr/bin/id
      register: who
    - name: debug
      debug:
        var: who
    - name: stat
      stat:
        path: "/root/x"


